### PR TITLE
1.16.2 implementation

### LINKED ISSUE #109: Does not work in 1.16.2
The plugin gets disabled and all red in the plugin list when using Spigot for 1.16.2.
Please a quick and fast fix is needed for this! I'm sure everyone agrees.

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
Download Link https://github.com/wherkamp/Holograms/releases/tag/2.13.1
Fixes: #109 
Works with 1.16.3
Edit 
SpigotMC resource for my Holograms Fork. https://www.spigotmc.org/resources/holograms.85800/

### CODE REVIEW

**Comment by starfury1927** [comment]
any plans for 1.16.4?

**Comment by wyatt-herkamp** [comment]
> any plans for 1.16.4?

Does it require an update. If so please tell me I will get right on it. 

I was just able to test it. I will have it available soon.

**Comment by gbidkar** [comment]
@wherkamp yes, it claims 1.16.4 needs an NMS update.

**Comment by wyatt-herkamp** [comment]
> @wherkamp yes, it claims 1.16.4 needs an NMS update.

I will try to have it done by the end of the day.

**Comment by wyatt-herkamp** [comment]
Here y'all go
https://github.com/wherkamp/Holograms/releases/tag/2.13.1

**Comment by gbidkar** [comment]
@wherkamp I recommend you make a new tag (2.13.2) and not override your existing one for sake of organization.
Anyways, I checked it against Spigot-1.16.4 and it works properly so far. Thanks a lot!! :)

**Comment by wyatt-herkamp** [comment]
SpigotMC resource for my Holograms Fork. https://www.spigotmc.org/resources/holograms.85800/

**Pull request closed without merging**
