### PR TITLE
Initial 1.15 support

### PR DESCRIPTION
**Pull request by niccholaspage**
This pull request includes support for the Minecraft 1.15 update. I've done some basic testing and it seems to be functioning properly. I also updated the dependency for 1.14 for the latest minor patch.

### CODE REVIEW

**Comment by DynamicDonkey** [comment]
@niccholaspage Would you mind releasing a zip for us to beta test? I have a full release of a server waiting on this plugin and I'll gladly use your version!

**Comment by niccholaspage** [comment]
A beta version of Holograms for 1.15 is available to download [here](https://github.com/niccholaspage/Holograms/releases). Let me know if you run into any issues.

**Comment by DynamicDonkey** [comment]
I ended up compiling it myself using the latest commit, and i can guarantee it works great! Thanks a bunch!

**Comment by sainttx** [comment]
Thanks for the update :)

**Pull request merged**
